### ISSUE TITLE
Issue with Special Characters

### ISSUE THREAD

**Issue by SjogrenDev** [gdarko/digital-license-manager#38] opened 2023-11-30 13:50 UTC
Hello,

I’ve encountered an issue while utilizing your plugin’s REST API endpoints, specifically when interacting with the **“/licenses/{license_key}”** endpoints. It appears that when the {license_key} contains certain special characters such as ‘@’, ‘/’, or others, it disrupts the API request flow, leading to an unexpected error:

```
{
  code: 'rest_no_route',
  message: 'No route was found matching the URL and request method.',
  data: { status: 404 }
}

```
**Steps to Reproduce:**

Use a {license_key} containing special characters like ‘@’, ‘/’, etc.
Make a request to any of the “licenses/{license_key}” endpoints via the REST API.

**Expected Behavior:**

The API should be able to process requests with {license_key} values containing special characters without encountering routing or handling issues.

**Additional Notes:**

I attempted to address this by using encodeURIComponent() to encode the special characters within the {license_key} before making the request. However, the issue persisted.

**Comment by gdarko** [comment] 2023-11-30 23:10
Hey @PunisherDev - 

I had a look at the issue. 

The problem is that we can not support / characters because those are reserved for the url delimiter. Isn't it possible to exclude those special characters from the generator character set?

Best,
Darko

**Comment by PunisherDev** [comment] 2023-12-01 12:26
> Hey @PunisherDev -
> 
> I had a look at the issue.
> 
> The problem is that we can not support / characters because those are reserved for the url delimiter. Isn't it possible to exclude those special characters from the generator character set?
> 
> Best, Darko

Hi @gdarko,

Seems like other symbols such as @ also break it. I guess you could start using query parameters instead so it would not cause issues.

I don't personally use your plugin, I just develop addons for it using your API. I heard that some of my clients are having issues as their license keys include the special characters. Most people use it to sell digital licenses not generated by themselves so they don't have control over the key format.

**Comment by gdarko** [comment] 2024-03-15 16:36
Hey @SjogrenDev  - 

We recently added some stuff for dealing with "Complex" keys.

Please check this:

https://docs.codeverve.com/digital-license-manager/rest-api/complex-licenses/

Best Regards,
Darko

**Comment by gdarko** [comment] 2024-07-24 17:10
Closing as complete. The above reply explains how to fix this problem.

**Closed by gdarko** 2024-07-24 17:10 UTC
Labels: bug
